on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1

      - name: Install Terraform
        run: |
          brew install tfenv
          tfenv install
      - run: bundle install --jobs 4 --retry 3 --deployment
      - run: bundle exec rake

